### PR TITLE
Add Bitcoin Transcripts section

### PR DESCRIPTION
**Pull request by michaelfolkson**
There is going to be some Optech formatting that I'm not yet following here. But the content is pretty much drafted. Opening this PR now so you can see the draft. Any initial thoughts or guidance towards the correct formatting would be gratefully received at this stage. I am available for the next few hours so I can work on finetuning this today.

### CODE REVIEW

**Comment by harding** [comment]
Merged with edits into https://github.com/bitcoinops/bitcoinops.github.io/pull/410 ; I broke up the edits over there into separate commits so you can see what I did (they'll be squashed at merge time), but if you're strapped for time https://github.com/bitcoinops/bitcoinops.github.io/pull/410/commits/2818909bbe9361a62bb6d2fd848c8e91ef008e5f contains all the non-trivial edits.  Please let me know if you object to any of the edits and I'll be happy to revert them.

Thanks for writing the section and typing the transcripts!

**Comment by michaelfolkson** [comment]
Certainly don't object to any of the edits. I thought Christian's swear word would need to get edited out ;) Please feel free to point out formatting things I'm not following though for future months (assuming this section continues). I'm wary of asking you to make the same formatting edits every month rather than opening a PR with all the correct Optech formatting myself.

**Comment by harding** [comment]
Formatting stuff is:

- [ ] Use lists, not paragraphs
- [ ] To the degree possible, title case proper nouns for packages (e.g. "Eclair" not "eclair"); we usually only use lowercase because it's necessary, e.g. command names (`bitcoind`) or marketing wackiness ("iPhone").  Most other things, such as protocol names, I try to get turned to common nouns (e.g. "payjoin").  Two exceptions there are "Bitcoin", the protocol, (to distinguish it from "bitcoin" the currency") and "MuSig" (because I was out-voted on my preference of "musig").
- [ ] Serial comma: a, b, and c (not a, b and c)
- [ ] Use reference-style links and put the URL definitions at the bottom
- [ ] Wrap lines at about 72 characters

You don't have to worry too much about my making those changes; I can do that with only a small fraction of my attention so really it was an opportunity to listen to an audiobook but record the time spent on it as productive Optech work. :-)  I've also been a professional writer for 15 years now and had to deal with many different publication's arbitrary style and formatting rules, and I know how frustrating that can be, so I'm never going to push authors to spend large amounts of their time learning my preferred rules when they're just submitting an occasional piece.

**Comment by michaelfolkson** [comment]
Ok thanks. I won't worry too much then but please don't hesitate to let me know whenever there is something particularly sloppy/lazy or that can save you some time on your end

**Pull request closed without merging**
